In [1]:
import numpy as np
from numpy.linalg import svd, matrix_rank

In [2]:
# rank=2の　３ｘ4行列を作成
A = np.array([[2, 4, 1, 3], [1, 5, 3, 2], [5, 7, 0, 7]])

In [3]:
print('matrix A\n', A)
print('rank: ', matrix_rank(A))

matrix A
 [[2 4 1 3]
 [1 5 3 2]
 [5 7 0 7]]
rank:  2


In [4]:
# singular value decomposition
u, s, vh = svd(A)
print('\nSVD result')
print('shape of u, s, vh:', u.shape, s.shape, vh.shape)
print('singular values:', s.round(2))


SVD result
shape of u, s, vh: (3, 3) (3,) (4, 4)
singular values: [13.39  3.58  0.  ]


In [5]:
# full_matrices=Falseの場合
u, s, vh = svd(A, full_matrices=False)
print('\nSVD result　(full_matrices: False)')
print('shape of u, s, vh:', u.shape, s.shape, vh.shape)


SVD result　(full_matrices: False)
shape of u, s, vh: (3, 3) (3,) (3, 4)


In [6]:
# 復元
# A_re = (u @ np.diag(s, -1)[1:] @ vh).round(2)
A_re = (u @ np.diag(s) @ vh).round(2)
print('\nreconstructed A:\n', A_re)


reconstructed A:
 [[ 2.  4.  1.  3.]
 [ 1.  5.  3.  2.]
 [ 5.  7. -0.  7.]]


In [7]:
u

array([[-0.40783698, -0.12444751,  0.90453403],
       [-0.40538262, -0.86299238, -0.30151134],
       [-0.81812831,  0.48964985, -0.30151134]])

In [9]:
vh

array([[-0.39682822, -0.70114979, -0.12132523, -0.57982456],
       [ 0.37306578, -0.38670052, -0.75749385,  0.37079333],
       [-0.82742746,  0.06343221, -0.18163613,  0.5275874 ]])